# Including static quantization and dynamic quantization
# stats-file generated by calibration is used for static quantization 
# quantize-eval is used for dynamic quantization
# To add more options such as per-channel...

import sys
import subprocess as sp
DATA_DIR = 'cifar10'
model = 'preact_resnet20_cifar'
pretrained_model = "checkpoint/preact_resnet20_cifar187_checkpoint.pth.tar"
out_dir = 'logs'
exp_name = 'qe'
use_swa_model = False
use_stats_file = True
stats_file = 'logs/quantization_stats.yaml'

if __name__ == "__main__":
    args = [f"{DATA_DIR}",
            f"--arch={model}",
            "-p 50",
            "-b 128",
            "--vs=0",
            "--evaluate",
            '--quantize-eval',
            "-j 1",
            f"--name={exp_name}",
            f"--out-dir={out_dir}"]
    extra_args = []

    if 'cifar' in DATA_DIR:
        extra_args.append(f"--resume-from={pretrained_model}")
    else:
        extra_args.append("--pretrained")
    if use_swa_model:
        extra_args.append("--use-swa-model")
    if use_stats_file:
        extra_args.append(f"--qe-stats-file={stats_file}")

    sp.call(["python", "classifier.py"] + args + extra_args)
    